### PR TITLE
♻️ (next): Change app target to the src directory

### LINKED ISSUE #32: Move next project to src
Refactor next project for incorpore the src directory and having more order

### PR DESCRIPTION
**Pull request by behagoras**
By moving the project to src our project will be eassier to read and be able to incorpore new modules like the catalog.js

### CODE REVIEW

**Comment by behagoras** [comment]
The src works fine but can't figure why the statics stops working, Is not a big issue because in the future We will use GCP Storage to manage static assets

**Review by WilliamVelazquez — CHANGES_REQUESTED** [review]
Everything is ok, but there is some settings for taking pages from src?

**Comment by WilliamVelazquez** [comment]
> The src works fine but can't figure why the statics stops working, Is not a big issue because in the future We will use GCP Storage to manage static assets

The Statics stop working because Next have a specific settings for the static and pages Folders, thas why I made the note about pages on the PR

**Comment by behagoras** [comment]
This will not be required, because the src folder will complicate the project, so I will close the pull request

**Pull request closed without merging**
